// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2j_TYQyw3LYvKD1u96w92vDOUUGIKvto',
    appId: '1:80845593370:web:fca05496737839d6476aa3',
    messagingSenderId: '80845593370',
    projectId: 'oauth-ff9d6',
    authDomain: 'oauth-ff9d6.firebaseapp.com',
    storageBucket: 'oauth-ff9d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2j_TYQyw3LYvKD1u96w92vDOUUGIKvto',
    appId: '1:80845593370:android:fca05496737839d6476aa3',
    messagingSenderId: '80845593370',
    projectId: 'oauth-ff9d6',
    authDomain: 'oauth-ff9d6.firebaseapp.com',
    storageBucket: 'oauth-ff9d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2j_TYQyw3LYvKD1u96w92vDOUUGIKvto',
    appId: '1:80845593370:ios:fca05496737839d6476aa3',
    messagingSenderId: '80845593370',
    projectId: 'oauth-ff9d6',
    storageBucket: 'oauth-ff9d6.firebasestorage.app',
    iosBundleId: 'com.oth.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2j_TYQyw3LYvKD1u96w92vDOUUGIKvto',
    appId: '1:80845593370:ios:fca05496737839d6476aa3',
    messagingSenderId: '80845593370',
    projectId: 'oauth-ff9d6',
    storageBucket: 'oauth-ff9d6.firebasestorage.app',
    iosBundleId: 'com.oth.fluttertest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2j_TYQyw3LYvKD1u96w92vDOUUGIKvto',
    appId: '1:80845593370:web:fca05496737839d6476aa3',
    messagingSenderId: '80845593370',
    projectId: 'oauth-ff9d6',
    authDomain: 'oauth-ff9d6.firebaseapp.com',
    storageBucket: 'oauth-ff9d6.firebasestorage.app',
  );
}
